apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: erashu/platformservice:latest
---
# this is seperation
apiVersion: v1
kind: Service
metadata:
  name: platforms-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platformservice
  ports:
  - name: platformservice
    protocol: TCP
    port: 80
    targetPort: 80  

# kubectl apply -f platforms-depl.yaml
# get all :
# kubectl get deployments
# kubectl delete deployments platforms-depl
# kubectl get pods
# kubectl get services
# kubectl get namespace

# To refresh the image on Kube
# kubectl rollout restart deployment platforms-depl

# For load balencer ingress-nginx
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.0.0/deploy/static/provider/cloud/deploy.yaml
# kubectl get pods --namespace=ingress-nginx
